---
title: "PNA Paper: Raji"
date: today
format: 
  html:
    code-fold: true
    code-overflow: wrap
    embed-resources: true
toc: true
execute:
    message: false
    warning: false
    error: false
    cache: true
---

Characterize the spatial landscape of Raji cells.

# Setup

Load helper functions

```{r}
#| label: setup

library(here)
here::i_am("raji/scripts/analysis.qmd")

# Load helper functions
source(here("raji/scripts/helpers.R"))
```

Load libraries

```{r}
#| label: load-libraries

library(tidyverse)
library(patchwork)
library(ggplotify)
library(ggplot2)
library(pixelatorR)
```

Define color palette

```{r}
#| label: define-color-palette

Pixelgen_accent_colors <-
  tibble::tibble(
    purples = c("#DED8F4", "#BFB3E9", "#A28EDB", "#866CCD", "#6C4ABD", "#5A3E9E", "#48327F"),
    blues = c("#B9CDED", "#92B0E0", "#6D92D1", "#4A73C0", "#2955AE", "#224792", "#1C3A76"),
    cyans = c("#D0EDE6", "#A2DACE", "#75C5B5", "#4AAF9D", "#209785", "#1B7E6F", "#156559"),
    greens = c("#D7EBD3", "#AFD6A9", "#86C080", "#5EA857", "#369030", "#2D7828", "#246120"),
    pinks = c("#F4DAEC", "#E7B7D7", "#DA94C1", "#CB73A9", "#BB5391", "#9C4579", "#7D3861"),
    reds = c("#F7BFC4", "#EF9DA2", "#E67C81", "#DB5D61", "#CE4042", "#A53335", "#7C2628"),
    oranges = c("#F6DBD4", "#EBB9AA", "#DE9982", "#D07B5B", "#C05F36", "#A04F2D", "#814024"),
    yellows = c("#FCE6B4", "#F7D78C", "#F0C966", "#E6BB43", "#DAAC22", "#AE8A1B", "#836714")
  )


col_fun <- circlize::colorRamp2(
  seq(from = -3, to = 3, length.out = 7),
  c(
    #"#1F395F", 
    #"#496389", 
    "#728BB1", 
    "#AABAD1", 
    "#DFE5EE", 
    "#FFFFFF", 
    #"#FFE0EA", 
    #"#E9AABF", 
    "#CD6F8D", 
    "#A23F5E", 
    "#781534")
)

```

# Load data

Load PXL data

```{r}
#| label: load-pxl-data

pxl_file_path <- here("data_untracked/raji/PNA062_Raji_1000cells_S06_S6.layout.pxl")

pg_data <- ReadPNA_Seurat(pxl_file_path)
pg_data
```

# Quality Control

## Molecule Rank Plot

```{r}
#| label: molecule-rank-plot

# Plot the molecule rank plot
(molecule_rank_plot <- MoleculeRankPlot(pg_data))
```
