---
title: "Brodin lab figures"
format:
  html:
    theme: cerulean
    page-layout: full
    embed-resources: true
    code_folding: show
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
  
---

# 



```{r load_packages, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE}

library(pixelatorR)
library(Seurat)
library(harmony)
library(tidyverse)
library(ggplotify)
library(tidygraph)
library(pcaMethods)
library(pbapply)
library(ggpubr)
library(ggrastr)
library(ggraph)
source("theme.R")
source("utility.R")
```


# Plotting

## Proximity and abundance 

```{r load_data, echo = FALSE, message = FALSE, warning = FALSE}

metadata <- 
  tibble(sample = c("S01_CP038_S1", "S02_CP038_S2", "S03_CP038_S3", "S04_CP038_S4"), 
         condition = c("SLE", "HC", "SLE", "HC"), 
         sample_alias = c("SLE1", "HC1", "SLE2", "HC2"))


B_cells <- 
  read_csv("../data/BrodinLab_pixelgen_data_forpublication/clustering_distribution_Bcells_CD21_CD72_toPixelgen.csv") %>% 
  pull(component) %>% 
  unique()

prox_data <- 
  read_csv("../data/BrodinLab_pixelgen_data_forpublication/cd21_cd72_unfiltered_proximity_scores.csv") %>% 
  filter(component %in% B_cells)

cells_in_data <- 
  prox_data$component %>% unique()

cells_meta <- 
  prox_data %>% 
  select(component, sample, condition) %>% 
  distinct() %>% 
  left_join(metadata) 

prox_data %>% 
  unite(contrast, marker_1, marker_2, sep = "/") %>% 
  left_join(metadata) %>% 
  ggplot(aes(condition, log2_ratio, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  # geom_point(data = . %>% 
  #              filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")),
  #            color = "red", size = 3) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~contrast) +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_violins.pdf", 
       width = 5, height = 3)

prox_data %>% 
  unite(contrast, marker_1, marker_2, sep = "/") %>% 
  left_join(metadata)


# h5ad data

adata <- 
  anndata::read_h5ad("../data/BrodinLab_pixelgen_data_forpublication/adata_bcells_toPixelgen.h5ad")

seur <- 
  CreateSeuratObject(t(adata$X)) %>% 
  NormalizeData(normalization.method = "CLR", margin = 2) %>% 
  subset(cells = cells_in_data) %>% 
  AddMetaData(metadata = cells_meta %>% 
                column_to_rownames("component")) 

LayerData(seur, "data")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>%
  ggplot(aes(condition, clr, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~marker) +
  theme_bw() +
  labs(x = NULL, y = "CLR") 

ggsave("../results/Brodin/brodin_abundance_violins.pdf", 
       width = 5, height = 3)


###
LayerData(seur, "data")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD21") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, clr)) +
  geom_point() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "CLR",
       title = "CD21") 



  
LayerData(seur, "count")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD21") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, count)) +
  geom_point() +
  scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "counts",
       title = "CD21") 
  

LayerData(seur, "count")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD21") %>% 
              rename(marker = marker_1)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, min_count)) +
  geom_point() +
  # scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(title = "CD21") 

prox_data %>% 
  ggplot(aes(join_count_expected_mean, join_count_z)) +
  geom_point()

LayerData(seur, "data")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD21") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  filter(component %in% cells_in_data) %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  # geom_point(data = . %>% 
  #              filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")),
  #            color = "red", size = 3) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~metric, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_abundance_prox_violins.pdf", 
       width = 6, height = 3)



LayerData(seur, "data")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  # filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2) %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  filter(component %in% cells_in_data) %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  # geom_point(data = . %>% 
  #              filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")),
  #            color = "red", size = 3) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_grid(metric ~ marker, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "value") 

ggsave("../results/Brodin/brodin_abundance_prox_violins_both.pdf", 
       width = 7, height = 6)


###

seur %>% 
  DensityScatterPlot(marker1 = "CD45", marker2 = "CD41", facet_vars = "condition") +
  geom_point(data = LayerData(seur) %>%
               t() %>% 
               as_tibble(rownames = "component") %>%
               filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")) %>% 
               left_join(cells_meta) %>% 
               rename(marker1 = CD45, marker2 = CD41),
             shape = 21, 
             size = 5,
             fill = NA,
             color = "red")


```


## auc

```{r auc, echo = FALSE, message = FALSE, warning = FALSE}

library(pROC)
temp_data <- 
  LayerData(seur, "data")[c("CD21", "CD72"), ] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  # filter(marker == "CD21") %>% 
  left_join(prox_data %>% 
              filter(marker_1 == marker_2) %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  filter(component %in% cells_in_data) %>% 
  mutate(value = ifelse(is.na(value), 0, value))

temp_data_CD21 <- 
  list(proximity = temp_data %>% 
         filter(marker == "CD21", metric == "log2_ratio"),
       abundance = temp_data %>% 
         filter(marker == "CD21", metric == "clr")) %>% 
  map(. %>% 
        mutate(rank = rank(value, ties.method = "first"),
               prob = rank/max(rank))) 
temp_auc <- 
  temp_data_CD21 %>% 
  map(. %>% 
        with(auc(condition, prob, levels = c("HC", "SLE"))) %>% 
        enframe(NULL, "auc") %>% 
        mutate(auc = as.numeric(auc))) %>% 
  bind_rows(.id = "metric") 

temp_data_CD21 %>%
  map(. %>% 
        arrange(value) %>% 
        roc("condition", "value", levels = c("HC", "SLE")) %>%
        coords %>% 
        arrange(sensitivity)) %>%
  bind_rows(.id = "metric") %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_step(direction = "vh") +
  geom_text(data = temp_auc, 
            aes(label = paste0("AUC = ", round(auc, 2))),
            x = 0.8, y = 0.1, size = 3) +
  # geom_point(size = 0.1) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  scale_x_continuous(limits = c(0, 1), expand = expansion(c(0.05, 0.05))) +
  scale_y_continuous(limits = c(0, 1), expand = expansion(c(0.05, 0.05))) +
  coord_fixed() +
  facet_wrap(~ metric) +
  theme_bw() +
  labs(x = "1 - specificity", y = "sensitivity",
       title = "ROC curve for CD21") 

ggsave("../results/Brodin/brodin_cd21_auc.pdf", 
       width = 5, height = 3)


temp_data_CD21 %>%
  map(. %>% 
        arrange(value) %>% 
        roc("condition", "value", levels = c("HC", "SLE")) %>%
        coords(ret = "all", transpose = FALSE)  %>% 
        arrange(sensitivity)) %>%
  bind_rows(.id = "metric") %>%
  ggplot(aes(x =recall, y = precision)) +
  geom_step(direction = "vh") +
  geom_text(data = temp_auc, 
            aes(label = paste0("AUC = ", round(auc, 2))),
            x = 0.8, y = 0.1, size = 3) +
  # geom_point(size = 0.1) +
  # geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  scale_x_continuous(limits = c(0, 1), expand = expansion(c(0.05, 0.05))) +
  scale_y_continuous(limits = c(0, 1), expand = expansion(c(0.05, 0.05))) +
  coord_fixed() +
  facet_wrap(~ metric) +
  theme_bw() +
  labs(x = "recall", y = "precision",
       title = "PR curve for CD21")

ggsave("../results/Brodin/brodin_cd21_pr.pdf", 
       width = 5, height = 3)
```

## 3D plotting

```{r 3d_plotting, echo = FALSE, message = FALSE, warning = FALSE}

plot_data <- 
  list(HC = read_csv("../data/BrodinLab_pixelgen_data_forpublication/3d_visualization_HC_high_clustering_layout_toPixelgen.csv"),
       SLE = read_csv("../data/BrodinLab_pixelgen_data_forpublication/3d_visualization_SLE_high_clustering_layout_toPixelgen.csv") %>% 
         rearrr::rotate_3d(
           x_col = "x",
           y_col = "y",
           z_col = "z",
           x_deg = 90,
           y_deg = 0,
           z_deg = 0,
           origin = c(0, 0, 0),
           keep_original = TRUE,
           overwrite = TRUE
         )) %>% 
  bind_rows(.id = "type")

# plot_data %>% 
#   filter(type == "SLE") %>% 
#   rearrr::rotate_3d(
#     x_col = "x",
#     y_col = "y",
#     z_col = "z",
#     x_deg = 80,
#     y_deg = 0,
#     z_deg = 0,
#     origin = c(0, 0, 0),
#     keep_original = TRUE,
#     overwrite = TRUE
#   ) %>% 
#   plotly::plot_ly(
#     x = ~x_rotated, 
#     y = ~y_rotated, 
#     z = ~z_rotated, 
#     color = ~CD21, 
#     size = ~z,
#     colors = c("gray", "orangered"),
#     type = "scatter3d",
#     mode = "markers",
#     marker = list(size = 2, opacity = 0.5)
#   ) 
# 
# plot_data %>% 
#   filter(type == "SLE") %>% 
#   as.data.frame() %>% 
#   rearrr::rotate_3d(
#     x_col = "x",
#     y_col = "y",
#     z_col = "z",
#     x_deg = 110,
#     y_deg = 0,
#     z_deg = 0,
#     origin = c(0, 0, 0),
#     keep_original = TRUE,
#     overwrite = TRUE
#   ) %>% 
#   arrange(z) %>% 
#   ggplot(aes(x = x_rotated, y = y_rotated, z = z_rotated)) +
#   geom_point(aes(color = CD21, size = z), alpha = 0.3) +
#   coord_fixed() +
#   scale_color_gradientn(colours = c("gray", "orangered")) +
#   scale_size(range = c(0.1, 3)) +
#   theme_void()



# plot_data %>%
#   mutate(x = ifelse(is.na(x_rotated), x, x_rotated),
#          y = ifelse(is.na(y_rotated), y, y_rotated),
#          z = ifelse(is.na(z_rotated), z, z_rotated)) %>% 
#   arrange(z) %>% 
#   # head(10000) %>% 
#   mutate(node_type = case_when(
#     CD41 == 1 ~ "CD41",
#     CD72 == 1 ~ "CD72",
#     CD21 == 1 ~ "CD21",
#     TRUE ~ "Other"
#   )) %>%
#   ggplot(aes(x, y)) +
#   geom_point(aes(color = node_type), 
#              size = 0.5) +
#   facet_wrap(~ type) +
#   scale_color_manual(values = c("CD72" = "#E67C81", "CD21" = "#6A9BD1", "Other" = "gray90", 
#                               "CD41" = "#A2D5AB")) +
#   coord_fixed() +
#   theme_void()
# 
# ggsave("../results/Brodin/brodin_3d_plot.pdf", 
#        width = 5, height = 3)

# LayerData(seur, "data")[, c("6b81434111175540", "8a5aa547e333b42c")] %>% 
#   as_tibble(rownames = "marker") %>% 
#   arrange(-`8a5aa547e333b42c`) %>% 
#   ggplot(aes(`6b81434111175540`, `8a5aa547e333b42c`)) +
#   geom_abline() +
#   geom_point(size = 0.1) +
#   geom_text(aes(label = marker)) +
#   coord_fixed() +
#   scale_x_continuous(limits = c(0, 6)) +
#   scale_y_continuous(limits = c(0, 6)) +
#   theme_bw()  



plot_data %>%
  mutate(x = ifelse(is.na(x_rotated), x, x_rotated),
         y = ifelse(is.na(y_rotated), y, y_rotated),
         z = ifelse(is.na(z_rotated), z, z_rotated)) %>%
  arrange(z) %>% 
  # head(10000) %>% 
  mutate(node_type = case_when(
    CD72 == 1 ~ "CD72",
    CD21 == 1 ~ "CD21",
    TRUE ~ "Other"
  )) %>% 
  ggplot(aes(x = x, y = y, fill = node_type, alpha = 0.9)) +
  geom_point_rast(aes(alpha = node_type, size = z),
                  shape = 21, stroke = 0.01, raster.dpi = 300) +
  facet_wrap(~ type) +
  scale_color_manual(values = c("CD72" = "#6A9BD1", "CD21" = "#E67C81", "Other" = "gray90")) +
  scale_fill_manual(values = c("CD72" = "#6A9BD1", "CD21" = "#E67C81", "Other" = "gray90")) +
  scale_alpha_manual(values = c("CD72" = 0.9, "CD21" = 0.9, "Other" = 0.2)) +
  scale_size(range = c(0.1, 1.5)) +
  # scale_color_gradientn(colours = c("#F2F2F2", "#F9D2DF", "#DB8CA6", "#AC4B69", "#781534")) +
  # scale_fill_gradientn(colours = c("#F2F2F2", "#F9D2DF", "#DB8CA6", "#AC4B69", "#781534")) +
  coord_fixed() +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = "white")) 

ggsave("../results/Brodin/brodin_3d_plot.pdf", 
       width = 8, height = 3)



```



# Revision

## B cell CD180 Proximity and abundance 

```{r load_data, echo = FALSE, message = FALSE, warning = FALSE}

metadata <- 
  tibble(sample = c("S01_CP038_S1", "S02_CP038_S2", "S03_CP038_S3", "S04_CP038_S4"), 
         condition = c("SLE", "HC", "SLE", "HC"), 
         sample_alias = c("SLE1", "HC1", "SLE2", "HC2"))

B_prox_data <- 
  read_csv("../data/sle_figure_candidates/Bcells/cd180_clustering_b_cells.csv") 

cells_meta <- 
  B_prox_data %>% 
  select(component, sample, condition) %>% 
  distinct() %>% 
  left_join(metadata) 

B_prox_data %>% 
  unite(contrast, marker_1, marker_2, sep = "/") %>% 
  left_join(metadata) %>% 
  ggplot(aes(condition, log2_ratio, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  # geom_point(data = . %>% 
  #              filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")),
  #            color = "red", size = 3) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~contrast) +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_CD180_violins.pdf", 
       width = 5, height = 3)

# h5ad data

adata <- 
  anndata::read_h5ad("../data/BrodinLab_pixelgen_data_forpublication/adata_bcells_toPixelgen.h5ad")

seur <- 
  CreateSeuratObject(t(adata$X)) %>% 
  NormalizeData(normalization.method = "CLR", margin = 2) %>% 
  AddMetaData(metadata = cells_meta %>% 
                column_to_rownames("component")) 

LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>%
  ggplot(aes(condition, clr, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~marker) +
  theme_bw() +
  labs(x = NULL, y = "CLR") 

ggsave("../results/Brodin/brodin_CD180_abundance_violins.pdf", 
       width = 5, height = 3)


###
LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD180") %>% 
  left_join(B_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD180") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, clr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "CLR",
       title = "CD180") 



  
LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD180") %>% 
  left_join(B_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD180") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, count)) +
  geom_point() +
  scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "counts",
       title = "CD180") 
  

LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD180") %>% 
  left_join(B_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD180") %>% 
              rename(marker = marker_1)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, min_count)) +
  geom_point() +
  # scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(title = "CD180") 

LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD180") %>% 
  left_join(B_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD180") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~metric, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_CD180_abundance_prox_violins.pdf", 
       width = 6, height = 3)



LayerData(seur, "data")[c("CD180"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  left_join(B_prox_data %>% 
              filter(marker_1 == marker_2) %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_grid(metric ~ marker, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "value") 

ggsave("../results/Brodin/brodin_CD180_abundance_prox_violins_both.pdf", 
       width = 7, height = 6)

prox_data %>% 
  bind_rows(B_prox_data) %>% 
  filter(marker_1 == marker_2) %>% 
  select(component, sample, condition, marker = marker_1, log2_ratio) %>% 
  pivot_wider(names_from = marker, values_from = log2_ratio) %>% 
  ggplot(aes(CD180, CD21, color = condition)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point() +
  geom_density2d() +
  facet_wrap(~condition) +
  coord_fixed() +
  theme_bw()
  

```

## Monocyte CD36 Proximity and abundance 

```{r load_data, echo = FALSE, message = FALSE, warning = FALSE}

metadata <- 
  tibble(sample = c("S01_CP038_S1", "S02_CP038_S2", "S03_CP038_S3", "S04_CP038_S4"), 
         condition = c("SLE", "HC", "SLE", "HC"), 
         sample_alias = c("SLE1", "HC1", "SLE2", "HC2"))

Mono_prox_data <- 
  read_csv("../data/sle_figure_candidates/Monocytes/cd36_clustering_monocytes_cells.csv")

cells_meta <- 
  Mono_prox_data %>% 
  select(component, sample, condition) %>% 
  distinct() %>% 
  left_join(metadata) 

Mono_prox_data %>% 
  unite(contrast, marker_1, marker_2, sep = "/") %>% 
  left_join(metadata) %>% 
  ggplot(aes(condition, log2_ratio, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  # geom_point(data = . %>% 
  #              filter(component %in% c("6b81434111175540", "8a5aa547e333b42c")),
  #            color = "red", size = 3) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~contrast) +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_CD36_violins.pdf", 
       width = 5, height = 3)

# h5ad data

adata <- 
  anndata::read_h5ad("../data/sle_figure_candidates/Monocytes/adata_monocytes_countdata_toPixelgen.h5ad")

seur <- 
  CreateSeuratObject(t(adata$X)) %>% 
  NormalizeData(normalization.method = "CLR", margin = 2) %>% 
  AddMetaData(metadata = cells_meta %>% 
                column_to_rownames("component")) 

LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>%
  ggplot(aes(condition, clr, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  # geom_jitter(aes(group = sample_alias), 
  #             position = position_jitterdodge(dodge.width = 0.85, 
  #                                             jitter.width = 0.1),
  #             size = 0.1) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~marker) +
  theme_bw() +
  labs(x = NULL, y = "CLR") 

ggsave("../results/Brodin/brodin_CD36_abundance_violins.pdf", 
       width = 5, height = 3)


###
LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD36") %>% 
  left_join(Mono_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD36") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, clr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "CLR",
       title = "CD36") 



  
LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD36") %>% 
  left_join(Mono_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD36") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, count)) +
  geom_point() +
  scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(x = "log2 ratio", y = "counts",
       title = "CD36") 
  

LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "count") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD36") %>% 
  left_join(Mono_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD36") %>% 
              rename(marker = marker_1)) %>% 
  mutate(log2_ratio = ifelse(is.na(log2_ratio), 0, log2_ratio)) %>%
  ggplot(aes(log2_ratio, min_count)) +
  geom_point() +
  # scale_y_log10() +
  facet_wrap(~condition) +
  theme_bw() +
  labs(title = "CD36") 

LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  filter(marker == "CD36") %>% 
  left_join(Mono_prox_data %>% 
              filter(marker_1 == marker_2, marker_1 == "CD36") %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_wrap(~metric, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio") 

ggsave("../results/Brodin/brodin_CD36_abundance_prox_violins.pdf", 
       width = 6, height = 3)



LayerData(seur, "data")[c("CD36"), , drop = FALSE] %>% 
  as_tibble(rownames = "marker") %>%
  pivot_longer(-marker, names_to = "component", values_to = "clr") %>%
  left_join(cells_meta) %>% 
  left_join(Mono_prox_data %>% 
              filter(marker_1 == marker_2) %>% 
              select(marker = marker_1, component, log2_ratio)) %>% 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") %>% 
  mutate(value = ifelse(is.na(value), 0, value)) %>% 
  ggplot(aes(condition, value, fill = condition)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample_alias), 
              draw_quantiles = 0.5) +
  ggbeeswarm::geom_beeswarm(aes(group = sample_alias),
                            dodge.width = 0.85, 
                            size = 0.1) +
  stat_compare_means(
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray90")) +
  scale_y_continuous(expand = expansion(c(0.05, 0.1))) +
  facet_grid(metric ~ marker, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = "value") 

ggsave("../results/Brodin/brodin_CD36_abundance_prox_violins_both.pdf", 
       width = 7, height = 6)


```


## UMAP and cell composition

```{r}
annotation_markers <-
  c("CD10", "CD117", "CD11a", "CD11b", 
    "CD11c", "CD123", "CD127", "CD138", "CD14", "CD141", "CD158", 
    "CD159a", "CD159c", "CD16", "CD19", "CD1c", "CD20", "CD24", "CD25", 
    "CD27", "CD28", "CD3e", "CD335", "CD337", "CD35", "CD38", 
    "CD4", "CD8", "CD45RA", "CD45RO", "CD56", "CD57", "CD58", "CD66b", "CD95", 
    "HLA-DR", "IgD", "TCRgd", "TCRva7.2", "TCRVd2", "TCRVg9", 
    "CD41", "CD9", 
    
    "TCRab", "CD45", "CD45RB", "CD2", "CD5", "CD26", "CD161", 
    "CD21", "CD22", "CD33", "CD79a", "CD7", "IgE", "IgM", "NKp80")

adata <- 
  anndata::read_h5ad("../data/BrodinLab_pixelgen_data_forpublication/h5ad_clustering_to_pixelgen/adata_counts_all_to_pixelgen.h5ad")


seur <- 
  CreateSeuratObject(t(adata$X)) %>% 
  NormalizeData(normalization.method = "CLR", margin = 2) |> 
  AddMetaData(metadata = read_csv("../data/BrodinLab_pixelgen_data_forpublication/h5ad_clustering_to_pixelgen/metadata_to_pixelgen.csv") %>% 
                column_to_rownames("component"))

set.seed(37)
seur <- 
  seur |> 
  NormalizeData(normalization.method = "CLR", margin = 2) %>%
  FindVariableFeatures(nfeatures = 75) %>%
  ScaleData() 

VariableFeatures(seur)[!VariableFeatures(seur) %in% annotation_markers]

seur <- 
  seur %>% 
  RunPCA(features = annotation_markers) %>%
  RunHarmony(
          group.by.vars = "sample",
          plot_convergence = FALSE,
        ) |> 
  RunUMAP(reduction = "harmony", dims = 1:15, n.neighbors = 15, seed.use = 37) |> 
  FindNeighbors(reduction = "harmony", dims = 1:15, k.param = 15) %>%
  FindClusters(resolution = 0.5, random.seed = 37)


seur[[]] |> 
  group_by(sample) |> 
  mutate(rank = rank(-n_umi)) |> 
  ggplot(aes(rank, n_umi)) +
  geom_point() +
  geom_hline(yintercept = 1e4) +
  scale_y_log10() +
  scale_x_log10()

Reductions(seur, "pca")@stdev %>% 
  enframe("PC", "sd") %>% 
  ggplot(aes(PC, sd)) +
  geom_line() +
  geom_point()
#   
# seur <- 
#   seur %>% 
#   FindNeighbors(reduction = "pca", dims = 1:15, k.param = 15) 

plot_embedding(seur, "umap",
               metavars = "condition",
               # pal = cell_palette,
               plot_title = "Clusters")

plot_embedding(seur, "umap",
               metavars = "CellType",
               pal = pbmc_cell_type_palette,
               plot_title = "samples") 

plot_embedding(seur, "umap",
               metavars = "seurat_clusters",
               plot_title = "samples") 


plot_data <- 
  seur %>% 
  Embeddings("umap") %>% 
  as_tibble(rownames = "component") %>% 
  left_join(FetchData(seur, c("sample", "condition", "CellType")) %>% 
              as_tibble(rownames = "component"))


plot_data %>% 
  ggplot(aes(umap_1, umap_2, color = CellType)) +
  # geom_path() +
  geom_point(size = 0.3) +
  geom_text(data = . %>% 
              group_by(CellType) %>%
              summarise(umap_1 = median(umap_1),
                        umap_2 = median(umap_2)),
            aes(label = CellType), 
            color = "black",
            size = 2, alpha = 0.5) +
  scale_color_manual(values = pbmc_cell_type_palette) +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(color = "Cell type",
       x = "UMAP 1",
       y = "UMAP 2") 

ggsave(
  filename = "../results/Brodin/UMAP_annotated_cells.pdf",
  width = 8,
  height = 8
)
ggsave(
  filename = "../results/Brodin/UMAP_annotated_cells_small.pdf",
  width = 5,
  height = 5
)


plot_data %>% 
  ggplot(aes(umap_1, umap_2, color = condition)) +
  geom_point(size = 0.3) +
  scale_color_manual(values = c("SLE" = "#E67C81", "HC" = "gray70")) +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(color = "Cell type",
       x = "UMAP 1",
       y = "UMAP 2") 

ggsave(
  filename = "../results/Brodin/UMAP_sle.pdf",
  width = 8,
  height = 8
)
ggsave(
  filename = "../results/Brodin/UMAP_sle_small.pdf",
  width = 5,
  height = 5
)

seur[[]] |> 
  as_tibble() |> 
  group_by(sample, condition, CellType) |> 
  count() |> 
  group_by(sample) |> 
  mutate(frac = n / sum(n)) |> 
  ungroup() |> 
  mutate(CellType = factor(CellType, names(pbmc_cell_type_palette))) |> 
  ggplot(aes(sample, frac, fill = CellType)) +
  geom_col() +
  geom_text(aes(label = paste0(round(100*frac, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  facet_grid(~ condition, scales = "free_x", space = "free") +
  scale_fill_manual(values = pbmc_cell_type_palette) +
  scale_y_continuous(labels = scales::percent_format(), 
                     expand = expansion(0)) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1),
    panel.grid = element_blank(),
    panel.border = element_blank()
    )
ggsave(
  filename = "../results/Brodin/cell_type_composition.pdf",
  width = 4,
  height = 5
)

VlnPlot(seur, "CD44", group.by = "CellType", split.by = "sample")

VlnPlot(seur, c("CD20", "CD19", "CD43", "CD44", "CD3e"), group.by = c("CellType", "sample"))
#, split.by = "sample")


```

#### Proximity Analysis

```{r}

prox <- read_csv("../data/BrodinLab_pixelgen_data_forpublication/h5ad_clustering_to_pixelgen/B_clustering.csv") |> 
  left_join(FetchData(seur, c("condition", "CellType", "n_umi")) |> 
              as_tibble(rownames = "component")) |> 
  mutate(p1 = marker_1_count / n_umi,
         p2 = marker_2_count / n_umi,
         pmin = ifelse(p1 < p2, p1, p2))


table(unique(prox$component) %in% colnames(seur))
n_distinct(prox$component)
# prox$component
prox$sample |> table()
prox$CellType |> table()

prox |> 
  mutate(type = ifelse(marker_1 == marker_2, "self", "cross")) |>
  ggplot(aes(pmin, fill = type)) +
  geom_vline(xintercept = c(0.001)) +
  geom_histogram(alpha = 0.5, 
                 position = position_dodge()) +
  scale_x_log10() +
  scale_x_log10() +
  labs(x = "Minimum marker frequency") +
  theme_bw() 

prox_sum <- 
  prox |> 
  filter(pmin > 0.001) |> 
  SummarizeProximityScores(group_vars = "condition") 


plot_markers <- 
  seur |> 
  subset(CellType == "B") |> 
  LayerData("data") |> 
  rowSums() |> 
  sort() |> 
  tail(20) |> 
  names()

plot_markers <- unique(c(plot_markers, "CD21", "CD180", "CD19", "CD81"))

plots <- 
  prox_sum$condition |> 
  unique() |> 
  set_names() |> 
  lapply(function(cond) {
    prox_sum |> 
      filter(condition == cond) |>
      filter(marker_1 %in% plot_markers,
             marker_2 %in% plot_markers) |> 
      mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 0.75, sign(mean_log2_ratio) * 0.75, mean_log2_ratio)) |> 
      ColocalizationHeatmap(value_col = "mean_log2_ratio", 
                            size_col = "pct_detected", 
                            size_range = c(4, 4),
                            colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                            type = "dots") +
      coord_fixed() +
      theme(panel.grid = element_blank()) +
      labs(title = cond)
    
  })

pdf(
  file = "../results/Brodin/B_cell_proximity_heatmap.pdf",
  width = 6,
  height = 5
)
plots
dev.off()

p1 <- 
  prox_sum |> 
  filter(condition == "SLE") |>
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |> 
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 0.8, sign(mean_log2_ratio) * 0.8, mean_log2_ratio)) |> 
  ColocalizationHeatmap(value_col = "mean_log2_ratio", 
                        size_col = "pct_detected", 
                        size_range = c(4, 4),
                        colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                        type = "dots") +
  coord_fixed() +
  theme(panel.grid = element_blank()) +
  labs(title = "SLE")

p2 <- 
  prox_sum |> 
  filter(condition == "HC") |>
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |> 
  mutate(marker_1 = factor(marker_1, levels(p1@data$marker_1)),
         marker_2 = factor(marker_2, levels(p1@data$marker_2))) |>
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 0.8, sign(mean_log2_ratio) * 0.8, mean_log2_ratio)) |> 
  ColocalizationHeatmap(value_col = "mean_log2_ratio", 
                        size_col = "pct_detected", 
                        cluster_cols = FALSE,
                        cluster_rows = FALSE,
                        size_range = c(4, 4),
                        colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                        type = "dots") +
  coord_fixed() +
  theme(panel.grid = element_blank()) +
  labs(title = "HC")

p2 | p1

ggsave(
  filename = "../results/Brodin/B_cell_proximity_heatmap_sidebyside.pdf",
  width = 12,
  height = 5
)

p3 <- 
  prox_sum |> 
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |> 
  mutate(marker_1 = factor(marker_1, levels(p1@data$marker_1)),
         marker_2 = factor(marker_2, levels(p1@data$marker_2))) |>
  select(condition, marker_1, marker_2, mean_log2_ratio) |>
  pivot_wider(names_from = condition, values_from = mean_log2_ratio) |>
  mutate(diff = SLE - HC) |> 
  mutate(diff = ifelse(abs(diff) > 0.5, sign(diff) * 0.5, diff)) |>
  ColocalizationHeatmap(value_col = "diff", 
                        size_col = "diff", 
                        cluster_cols = FALSE,
                        cluster_rows = FALSE,
                        size_range = c(4, 4),
                        colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                        type = "dots") +
  coord_fixed() +
  theme(panel.grid = element_blank()) +
  labs(title = "SLE - HC")

p3
ggsave(
  filename = "../results/Brodin/B_cell_proximity_heatmap_difference.pdf",
  width = 6,
  height = 5
)

prox_pca <- 
  prox |> 
  # filter(marker_1 %in% plot_markers,
  #        marker_2 %in% plot_markers) |> 
  filter(pmin > 0.001) |>
  select(marker_1, marker_2, log2_ratio, component) |> 
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |> 
  column_to_rownames("component") |> 
  pcaMethods::pca(nPcs = 10, scale = "none")

prox_pca@loadings |> 
  as_tibble(rownames = "pair") |> 
  arrange(-abs(PC1))


prox_pca@loadings |> 
  as_tibble(rownames = "pair") |> 
  arrange(-abs(PC2))

prox_pca@loadings |> 
  as_tibble(rownames = "pair") |> 
  arrange(-abs(PC2))

prox_pca@loadings |> 
  as_tibble(rownames = "pair") |> 
  select(pair, value = PC8) |> 
  arrange(-abs(value)) |> 
  head(40) |> 
  separate(pair, into = c("marker_1", "marker_2"), sep = "/") |> 
  as_tbl_graph() |> 
  mutate(degree = centrality_degree()) |>
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = abs(value),
                     edge_width = abs(value),
                     edge_color = value)) +
  geom_node_point(aes(size = degree), color = "gray20") +
  geom_node_text(aes(label = name), vjust = 1.5, size = 3) +
  scale_edge_color_gradientn(colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                             name = "PC2 loading") +
  scale_edge_width(range = c(0.2, 2), name = "PC2 loading") +
  scale_edge_alpha(range = c(0.2, 1), name = "PC2 loading") +
  theme_void() +
  coord_fixed() +
  labs(title = "B cell proximity PCA - PC2 loadings")



prox_pca@scores |> 
  as_tibble(rownames = "component") |>
  left_join(FetchData(seur, c("condition")) |> 
              as_tibble(rownames = "component")) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point() +
  geom_vline(xintercept = -2.5, linetype = "dashed") +
  facet_wrap(~condition) +
  theme_bw() +
  coord_fixed() +
  labs(x = "PC1", y = "PC2",
       title = "B cell proximity PCA")

prox_pca@scores |> 
  as_tibble(rownames = "component") |>
  left_join(FetchData(seur, c("condition", "CD3e")) |> 
              as_tibble(rownames = "component")) |> 
  ggplot(aes(PC1, CD3e)) +
  geom_point() +
  facet_wrap(~condition) 

cells_of_interest <- 
  prox_pca@scores |> 
  as_tibble(rownames = "component") |>
  filter(PC1 < -5) |> 
  pull(1)
  
prox |> 
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |>
  filter(pmin > 0.001) |>
  mutate(highlight = ifelse(component %in% cells_of_interest, "PC1 outliers", "Others")) |>
  SummarizeProximityScores(group_vars = "highlight") |> 
  group_by(marker_1, marker_2) |> 
  filter(any(mean_log2_ratio > 0.5)) |> 
  select(marker_1, marker_2, highlight, mean_log2_ratio) |> 
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 2, sign(mean_log2_ratio) * 2, mean_log2_ratio)) |>
  as_tbl_graph() |> 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_color = mean_log2_ratio)) +
  geom_node_point(size = 2, color = "gray20") +
  geom_node_text(aes(label = name), vjust = 1.5, size = 3) +
  facet_wrap(~highlight) +
  scale_edge_color_gradientn(colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                             limits = c(-2, 2),
                             name = "Mean log2 ratio") +
  # scale_edge_width(range = c(0.2, 2), name = "Mean log2 ratio") +
  scale_edge_alpha(range = c(0.2, 1), name = "Mean log2 ratio") +
  theme_void() +
  coord_fixed() +
  labs(title = "B cell proximity network\n(highlighted: cells with low PC1 scores)")

# PLS

library(pls)

X <-
  prox |> 
  # filter(marker_1 %in% plot_markers,
  #        marker_2 %in% plot_markers) |> 
  filter(pmin > 0.01) |>
  select(marker_1, marker_2, log2_ratio, component) |> 
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |> 
  column_to_rownames("component") |> 
  as.matrix()

Y <- 
  FetchData(seur, "condition") %>% 
  mutate(condition = ifelse(condition == "SLE", 1, 0)) %>%
  as.matrix()

Y <- Y[rownames(X), ,drop = FALSE]

pls_data <- 
  plsr(
    Y ~ X,
    ncomp = 2
  )

pls_data$loadings[, 1:2] |> 
  as_tibble(rownames = "pair") |> 
  select(pair, value = 3) |> 
  # arrange(-abs(value)) 
  head(60) |> 
  separate(pair, into = c("marker_1", "marker_2"), sep = "/") |> 
  as_tbl_graph() |> 
  mutate(degree = centrality_degree()) |>
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = abs(value),
                     edge_width = abs(value),
                     edge_color = value)) +
  geom_node_point(aes(size = degree), color = "gray20") +
  geom_node_text(aes(label = name), vjust = 1.5, size = 3) +
  scale_edge_color_gradientn(colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                             name = "PC2 loading") +
  scale_edge_width(range = c(0.2, 2), name = "PC2 loading") +
  scale_edge_alpha(range = c(0.2, 1), name = "PC2 loading") +
  theme_void() +
  coord_fixed() +
  labs(title = "B cell proximity PCA - PC2 loadings")

pls_data$scores[, 1:2] |> 
  as_tibble(rownames = "component") |>
  left_join(FetchData(seur, c("condition")) |> 
              as_tibble(rownames = "component")) %>%
  ggplot(aes(`Comp 1`, `Comp 2`)) +
  geom_point() +
  geom_vline(xintercept = 2.5, linetype = "dashed") +
  geom_hline(yintercept = 2.5, linetype = "dashed") +
  facet_wrap(~condition) +
  theme_bw() +
  coord_fixed() +
  labs(x = "PLS1", y = "PLS2",
       title = "B cell proximity PCA")


markers_of_interest <- c("CD22","CD21", "CD35", "IgM")
pls_data$scores[, 1:2] |> 
  as_tibble(rownames = "component") |>
  left_join(FetchData(seur, c("condition")) |> 
              as_tibble(rownames = "component")) %>%
  left_join(prox |> 
              filter(marker_1 %in% markers_of_interest, 
                     marker_2 %in% markers_of_interest)) |> 
  unite(pair, marker_1, marker_2, sep = "/") %>%
  ggplot(aes(`Comp 1`, `Comp 2`, color = log2_ratio)) +
  geom_point(size = 1) +
  geom_vline(xintercept = -2.5, linetype = "dashed") +
  facet_wrap(~pair) +
  scale_color_gradientn(colors = pixelatorR::PixelgenGradient(100, "BluesCherry")) +
  theme_bw() +
  coord_fixed() +
  labs(x = "PC1", y = "PC2",
       title = "B cell proximity PCA")

cells_of_interest <-
  pls_data$scores[, 1:2] |> 
  as_tibble(rownames = "component") |> 
  filter(`Comp 1` > 2.5, 
         `Comp 2` < 2.5) |> 
  pull(1)


prox |> 
  filter(pmin > 0.0025) |>
  filter(
    
    (marker_1 == "CD21" & marker_2 == "CD35") |
      (marker_1 == marker_2 & marker_1 %in% c("CD21", "CD35", "IgM", "HLA-DR", "CD180"))
           ) |> 
  mutate(highlight = ifelse(component %in% cells_of_interest, "PC1 outliers", "Others")) |>
  select(component, marker_1, marker_2, highlight, log2_ratio) |>
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |>
  pivot_longer(-c(component, highlight), names_to = "pair", values_to = "log2_ratio") %>%
  ggplot(aes(highlight, log2_ratio, fill = highlight)) +
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = highlight), draw_quantiles = 0.5) +
  geom_jitter(aes(group = highlight), 
              position = position_jitterdodge(dodge.width = 0.85, jitter.width = 0.1),
              size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("Others", "PC1 outliers")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("PC1 outliers" = "red", "Others" = "gray80")) +
  facet_wrap(~pair, ncol = 2) +
  theme_bw() +
  labs(x = NULL, y = "log2 ratio",
       title = "B cell proximity PCA - PC1 outliers")

FetchData(seur, c("CD2", "CD3e", "condition", "CellType"), layer = "data") |> 
  as_tibble(rownames = "component") |> 
  pivot_longer(-c(component, condition, CellType), names_to = "marker", values_to = "clr") |>
  filter(CellType %in% c("B")) |> 
  mutate(highlight = ifelse(component %in% cells_of_interest, "PC1 outliers", "Others")) |>
  ggplot(aes(highlight, clr, fill = highlight)) +
  geom_violin(aes(group = highlight), draw_quantiles = 0.5) +
  geom_jitter(aes(group = highlight), 
              position = position_jitterdodge(dodge.width = 0.85, jitter.width = 0.1),
              size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("Others", "PC1 outliers")),
    method = "wilcox.test", 
    size = 3) +
  scale_fill_manual(values = c("PC1 outliers" = "red", "Others" = "gray80")) +
  facet_grid(marker~condition) +
  theme_bw() +
  labs(x = NULL, y = "CD3e CLR",
       title = "B cell proximity PCA - PC1 outliers")
  
prox |> 
  filter(pmin > 0.001) |>
  mutate(highlight = ifelse(component %in% cells_of_interest, "PC1 outliers", "Others")) |> 
  inner_join(pls_data$loadings[, 1:2] |> 
               as_tibble(rownames = "pair") |> 
               select(pair, value = 3) |> 
               filter(abs(value) > 0.1) |> 
               separate(pair, into = c("marker_1", "marker_2"), sep = "/")) |> 
  select(component, marker_1, marker_2, log2_ratio) |>
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |> 
  column_to_rownames("component") %>%
  pheatmap::pheatmap(
    annotation_row = tibble(
      component = rownames(.)
    ) |> 
      mutate(highlight = ifelse(component %in% cells_of_interest, "PC1 outliers", "Others")) |>  
      left_join(FetchData(seur, c("condition")) |> 
                  as_tibble(rownames = "component")) |>
      column_to_rownames("component")
                            
  )


diff_prox <- 
  prox |> 
  filter(pmin > 0.0025) |>
  DifferentialProximityAnalysis(
    proximity_metric = "log2_ratio",
    backed = "data.table",
    min_n_obs = 10,
    contrast_column = "condition",
    reference = "HC")

diff_prox |> 
  ggplot(aes(diff_median, -log10(p_adj))) +
  geom_point(size = 0.1) +
  geom_text(
    data = . %>% 
      filter(p_adj < 0.05,
             abs(diff_median) > 0.25),
    aes(label = paste0(marker_1, "/", marker_2)),
    vjust = 1.5, size = 3
  ) +
  theme_bw()
ggsave(
  filename = "../results/Brodin/B_cell_proximity_differential_proximity_volcano.pdf",
  width = 6,
  height = 5
)

diff_prox2 <- 
  prox |> 
  filter(pmin > 0.0025) |>
  filter(!component %in% cells_of_interest) |> 
  DifferentialProximityAnalysis(
    proximity_metric = "log2_ratio",
    backed = "data.table",
    min_n_obs = 10,
    contrast_column = "condition",
    reference = "HC")

diff_prox2 |> 
  ggplot(aes(diff_median, -log10(p_adj))) +
  geom_point() +
  geom_text(
    data = . %>% 
      filter(p_adj < 0.05),
    aes(label = paste0(marker_1, "/", marker_2)),
    vjust = 1.5, size = 3
  )


prox |> 
  filter(pmin > 0.001) |>
  mutate(highlight = ifelse(component %in% cells_of_interest, "Outliers", "Others")) |> 
  inner_join(diff_prox |> 
               filter(p_adj < 0.01) |>
               select(marker_1, marker_2)) |> 
  select(component, marker_1, marker_2, log2_ratio) |>
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |> 
  left_join(FetchData(seur, c("CD3e", "CD2", "CD20", "CD19", "CD41", "CD9"), 
                      layer = "data") |> 
              scale() |>
              as_tibble(rownames = "component")) |>
  column_to_rownames("component") %>%
  pheatmap::pheatmap(
    annotation_row = tibble(
      component = rownames(.)
    ) |> 
      mutate(highlight = ifelse(component %in% cells_of_interest, "Outliers", "Others")) |>  
      left_join(FetchData(seur, c("condition")) |> 
                  as_tibble(rownames = "component")) |>
      column_to_rownames("component"),
    cutree_rows = 2
                            
  )
 
  

prox |> 
  filter(pmin > 0.001) |>
  filter(!component %in% cells_of_interest) |> 
  mutate(highlight = ifelse(component %in% cells_of_interest, "Outliers", "Others")) |> 
  inner_join(diff_prox2 |> 
               filter(p_adj < 0.01) |>
               select(marker_1, marker_2)) |> 
  select(component, marker_1, marker_2, log2_ratio) |>
  unite(pair, marker_1, marker_2, sep = "/") %>%
  pivot_wider(names_from = pair, values_from = log2_ratio, values_fill = 0) |> 
  left_join(FetchData(seur, c("CD3e", "CD2", "CD20", "CD19", "CD41", "CD9"), 
                      layer = "data") |> 
              scale() |>
              as_tibble(rownames = "component")) |>
  column_to_rownames("component") %>%
  pheatmap::pheatmap(
    annotation_row = tibble(
      component = rownames(.)
    ) |> 
      mutate(highlight = ifelse(component %in% cells_of_interest, "Outliers", "Others")) |>  
      left_join(FetchData(seur, c("condition")) |> 
                  as_tibble(rownames = "component")) |>
      column_to_rownames("component"),
    cutree_rows = 2
                            
  )
 
  


prox |> 
  filter(pmin > 0.001) |>
  mutate(highlight = ifelse(component %in% cells_of_interest, "Outliers", "Others")) |> 
  SummarizeProximityScores(group_vars = "highlight") |>
  filter(mean_log2_ratio > 0.5) |> 
  select(marker_1, marker_2, highlight, mean_log2_ratio) |> 
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 2, sign(mean_log2_ratio) * 2, mean_log2_ratio)) |>
  as_tbl_graph() |> 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_color = mean_log2_ratio)) +
  geom_node_point(size = 2, color = "gray20") +
  geom_node_text(aes(label = name), vjust = 1.5, size = 3) +
  facet_wrap(~highlight) +
  scale_edge_color_gradientn(colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                             limits = c(-2, 2),
                             name = "Mean log2 ratio") +
  # scale_edge_width(range = c(0.2, 2), name = "Mean log2 ratio") +
  scale_edge_alpha(range = c(0.2, 1), name = "Mean log2 ratio") +
  theme_void() +
  coord_fixed() +
  labs(title = "B cell proximity network\n(highlighted: cells with low PLS1 scores)")



prox_sum2 <- 
  prox |> 
  filter(!component %in% cells_of_interest) |>
  filter(pmin > 0.001) |> 
  SummarizeProximityScores(group_vars = "condition") 


p1 <- 
  prox_sum2 |> 
  filter(condition == "SLE") |>
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |> 
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 0.8, sign(mean_log2_ratio) * 0.8, mean_log2_ratio)) |> 
  ColocalizationHeatmap(value_col = "mean_log2_ratio", 
                        size_col = "pct_detected", 
                        size_range = c(4, 4),
                        colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                        type = "dots") +
  coord_fixed() +
  theme(panel.grid = element_blank()) +
  labs(title = "SLE")

p2 <- 
  prox_sum2 |> 
  filter(condition == "HC") |>
  filter(marker_1 %in% plot_markers,
         marker_2 %in% plot_markers) |> 
  mutate(marker_1 = factor(marker_1, levels(p1@data$marker_1)),
         marker_2 = factor(marker_2, levels(p1@data$marker_2))) |>
  mutate(mean_log2_ratio = ifelse(abs(mean_log2_ratio) > 0.8, sign(mean_log2_ratio) * 0.8, mean_log2_ratio)) |> 
  ColocalizationHeatmap(value_col = "mean_log2_ratio", 
                        size_col = "pct_detected", 
                        cluster_cols = FALSE,
                        cluster_rows = FALSE,
                        size_range = c(4, 4),
                        colors = pixelatorR::PixelgenGradient(100, "BluesCherry"),
                        type = "dots") +
  coord_fixed() +
  theme(panel.grid = element_blank()) +
  labs(title = "HC")

p2 | p1

ggsave(
  filename = "../results/Brodin/B_cell_proximity_heatmap_sidebyside_filt.pdf",
  width = 12,
  height = 5
)

some_markers <- 
  diff_prox |> 
  filter(p_adj < 0.001,
         diff_median > 0.25) |> 
  select(marker_1, marker_2) |> 
  unlist() |> 
  unique()

FetchData(seur, c("condition", "sample", "CellType", some_markers)) |> 
  as_tibble(rownames = "component") |> 
  filter(CellType == "B") |> 
  pivot_longer(-c(component, condition, sample, CellType), names_to = "marker", values_to = "clr") |>
  ggplot(aes(condition, clr, group = sample, fill = condition))+
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample), draw_quantiles = 0.5) +
  geom_jitter(aes(group = sample), 
              position = position_jitterdodge(dodge.width = 0.85, jitter.width = 0.1),
              size = 0.2, alpha = 0.5) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  facet_wrap(~marker, scales = "free_y") +
  scale_y_continuous(expand = expansion(c(0.05, 0.2))) + 
  theme_bw() +
  labs(x = NULL, y = "CLR",
       title = "Marker expression by condition") +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray70"))

FetchData(seur, c("condition", "sample", "CellType", some_markers)) |> 
  as_tibble(rownames = "component") |> 
  filter(CellType == "B") |> 
  pivot_longer(-c(component, condition, sample, CellType), names_to = "marker", values_to = "clr") |> 
  left_join(prox |> 
              filter(marker_1 %in% some_markers,
                     marker_2 %in% some_markers, 
                     marker_1 == marker_2) |> 
              filter(pmin > 0.001) |> 
              select(component, marker = marker_1, log2_ratio)) |> 
  pivot_longer(c(clr, log2_ratio), names_to = "metric", values_to = "value") |>
  mutate(value = ifelse(is.na(value), 0, value)) |>
  ggplot(aes(condition, value, group = sample, fill = condition))+
  geom_hline(yintercept = 0) +
  geom_violin(aes(group = sample), draw_quantiles = 0.5) +
  ggbeeswarm::geom_beeswarm(aes(group = sample),
                            dodge.width = 0.9,
                            corral.width = 0.45, 
                            size = 0.1) +
  stat_compare_means(
    # aes(label = ..p.format..), 
    comparisons = list(c("HC", "SLE")),
    method = "wilcox.test", 
    size = 3) +
  facet_grid(metric~marker, scales = "free_y") +
  scale_y_continuous(expand = expansion(c(0.05, 0.2))) + 
  theme_bw() +
  labs(x = NULL, y = "Value") +
  scale_fill_manual(values = c("SLE" = "#E67C81", "HC" = "gray70"))

ggsave(
  filename = "../results/Brodin/B_cell_marker_expression_and_proximity_by_condition.pdf",
  width = 18,
  height = 5
)
```

